name: cold_mailing
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  text_divider: ^1.0.0
  stacked: ^2.0.0
  video_player: ^2.3.0
  cupertino_icons: ^1.0.2
  flutter_gen: ^5.4.0
  remixicon: ^1.0.0
  animated_bottom_navigation_bar: ^1.3.2
  flutter_bloc: ^8.1.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.8

dependency_overrides:
flutter_gen:
    output: lib/gen/
    line_length: 80
    colors:
      outputs:
        class_name: AppColors
      inputs:
        - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/icons/onboarding/
    - assets/icons/auth/
    - assets/icons/home/
    - assets/Splash/
